# Generated by Django 2.2.2 on 2019-07-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OWDR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='OWDR.Target'),
            preserve_default=False,
        ),
    ]
