# Generated by Django 2.2.2 on 2019-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWDR', '0002_auto_20190710_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tye', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='gift',
            name='items',
            field=models.ManyToManyField(to='OWDR.Item'),
        ),
    ]
