# Generated by Django 2.2.2 on 2019-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWDR', '0003_auto_20190710_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tye',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='ItemDescription',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
