# Generated by Django 2.2.2 on 2019-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWDR', '0004_auto_20190710_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='picked_up_date',
            field=models.DateField(blank=True),
        ),
    ]
