# Generated by Django 2.2.2 on 2019-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWDR', '0005_auto_20190717_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='picked_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
