# Generated by Django 2.2.2 on 2019-07-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OWDR', '0006_auto_20190717_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
